M48
; DRILL file {KiCad (6.0.8-1)-1} date Thursday, 24 November 2022 at 03:45:06
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-24T03:45:06+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8-1)-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X25.0Y-33.5
X35.0Y-85.0
X69.2Y-45.6
X86.0Y-96.0
T0
M30
