#ifndef __PLATFORM_OPTS_H__
#define __PLATFORM_OPTS_H__

#define DEBUG_SERIAL_USART_TX_BUFFER_SIZE 256
#define DEBUG_SERIAL_USART_RX_BUFFER_SIZE 16
#define DEBUG_SERIAL_TX_BUFFER_SIZE 1024
#define DEBUG_SERIAL_RX_BUFFER_SIZE 16

#define DBG_SERIAL_ENABLE_DMA 1
#define DBG_SERIAL_SHOW_INFO 1

#define ETHERNETIF_SERVICE_PERIOD 200

//disks
#define FLASH_W25QX_MODEL 128

//USB FS
#define USE_USB_OTG_FS 
#define USE_EMBEDDED_PHY 
#define USE_DEVICE_MODE 


#endif
