#ifndef __PLATFORM_OPTS_H__
#define __PLATFORM_OPTS_H__

#define DEBUG_USART_TXDMA_BUFFER_SIZE 256
#define DEBUG_USART_RXDMA_BUFFER_SIZE 16
#define DEBUG_SERIAL_TX_BUFFER_SIZE 1024
#define DEBUG_SERIAL_RX_BUFFER_SIZE 32

#define DBG_SERIAL_ENABLE_DMA 1
#define DBG_SERIAL_SHOW_INFO 1

<<<<<<< HEAD
#define DEVICE_CAM_OV2640_DEBUG 0
#define NETCONF_CHECK_LINK_PERIOD 200

#define DHCP_EN 1
#define DNS_DEFAULT_SERVER_0 "8.8.8.8"
#define DNS_DEFAULT_SERVER_1 "8.8.4.4"
=======
#define DEBUG_USART3_TX_BUFFER_SIZE 256
#define DEBUG_USART3_RX_BUFFER_SIZE 16
#define DEBUG_SERIAL_TX_BUFFER_SIZE 1024
#define DEBUG_SERIAL_RX_BUFFER_SIZE 32
>>>>>>> MDK_REV200_BSP

#endif
