#ifndef __PLATFORM_OPTS_H__
#define __PLATFORM_OPTS_H__

#define DBG_SERIAL_ENABLE_DMA 1
#define DBG_SERIAL_SHOW_INFO 1

#define DEVICE_CAM_OV2640_DEBUG 0
#define NETCONF_CHECK_LINK_PERIOD 200

#endif
